default: &default
  dispatchers:
    - polling_interval: 0.1
      batch_size: 10
  workers:
    - queues:
        - default
      threads: 5
      processes: 2
      polling_interval: 0.1
    - queues:
        - anthropic
      threads: 1
      processes: 1
      polling_interval: 1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default